web:
    build: web
    volumes:
        - ./data/www:/var/www/html/
    ports:
        - "80:80"
    links:
        - mysql
mysql:
    build: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: drupal8
        MYSQL_ALLOW_EMPTY_PASSWORD: no
    ports:
        - "3306:3306"
